import type { Metadata } from "next";
import localFont from "next/font/local";
import ThemeWrapper from "../components/ThemeWrapper";
import { Header } from "../components/ui/Header";
import {ModalProvider} from "../components/ui/Modal";

import {themeDark} from "../components/ui/themes";

const sourceSansFont = localFont({
	src: [
		{
			path: "./fonts/SourceSansPro/SourceSansPro-ExtraLight.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-ExtraLightItalic.ttf",
			weight: "200",
			style: "italic",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-LightItalic.ttf",
			weight: "300",
			style: "italic",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-Italic.ttf",
			weight: "400",
			style: "italic",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "./fonts/SourceSansPro/SourceSansPro-SemiBoldItalic.ttf",
			weight: "600",
			style: "italic",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<ThemeWrapper font={sourceSansFont.className} theme={themeDark}>
			<Header/>
			<ModalProvider>
				{children}
			</ModalProvider>
		</ThemeWrapper>
	);
}
