import type { Metadata } from "next";
import {sourceSansFont} from "../utils/fonts";
import ThemeWrapper from "../components/ThemeWrapper";
import {AuthWrapper} from "../components/AuthWrapper";
import { Header } from "../components/ui/Header";
import {ModalProvider} from "../components/ui/Modal";
import {themeDark} from "../components/ui/themes";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<ThemeWrapper font={sourceSansFont.className} theme={themeDark}>
			<AuthWrapper>
				<Header/>
				<ModalProvider>
					{children}
				</ModalProvider>
			</AuthWrapper>
		</ThemeWrapper>
	);
}
